# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox" do
  version "0.8.2"

  on_macos do
    on_intel do
      url "https://github.com/tiborhercz/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_amd64.tar.gz"
      sha256 "1c7c3aafca9f13bbf1e4937f4710d609cd0deca0ee6f520878d0e82657d98e49"
    end
    on_arm do
      url "https://github.com/tiborhercz/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_arm64.tar.gz"
      sha256 "d3ce6b02652b91ad3c7382d855f3bb214bcd3f04729051ff796131a4000c9d03"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tiborhercz/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_amd64.tar.gz"
      sha256 "e8a02d44bc1bca1bfd3101fa4062d25a9c57c059a0047725c532ed94cbfdeefc"
    end
    on_arm do
      url "https://github.com/tiborhercz/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_arm64.tar.gz"
      sha256 "e9010dc037c665a396c945bcf4e6dfd47f6287e96dc463bc7d19213860617e4c"
    end
  end

  name "toolbox"
  desc "A collection of various cli tools"
  homepage "https://github.com/tiborhercz/toolbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox"

  # No zap stanza required

end
