# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox" do
  version "0.8.1"

  on_macos do
    on_intel do
      url "https://github.com/tiborhercz/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_amd64.tar.gz"
      sha256 "f9ceff05456aa31dbf8dab7928498f7a4ef471f572311ead837f5e648afaa8fd"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the toolbox
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tiborhercz/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_amd64.tar.gz"
      sha256 "5ed31dd79223508d284166f1e30232022a9c7d0d767f5296ae4bc22be9705af1"
    end
  end

  name "toolbox"
  desc "A collection of various cli tools"
  homepage "https://github.com/tiborhercz/toolbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox"

  # No zap stanza required

end
