# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox" do
  version "0.8.0"

  on_macos do
    on_intel do
      url "https://github.com/tiborhercz/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_amd64.tar.gz"
      sha256 "4f3fe541380f65ff567339f253b784583b08b2067ae4da5f4e3c1f45a7222c45"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the toolbox
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tiborhercz/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_amd64.tar.gz"
      sha256 "0728a9bf6f1d17a74253564b77cd59aa42ba86b8bfc1d8e90a6fde7328c0c506"
    end
  end

  name "toolbox"
  desc "A collection of various cli tools"
  homepage "https://github.com/tiborhercz/toolbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox"

  # No zap stanza required

end
