# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolbox < Formula
  desc "A collection of various cli tools"
  homepage "https://github.com/tiborhercz/toolbox"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiborhercz/toolbox/releases/download/v0.8.1/toolbox_0.8.1_darwin_amd64.tar.gz"
      sha256 "da654d0fc1ca2d9d7b09b64992babed7e75b9d2b7d215cf806f0aea27b94b1e6"

      define_method(:install) do
        bin.install "toolbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiborhercz/toolbox/releases/download/v0.8.1/toolbox_0.8.1_darwin_arm64.tar.gz"
      sha256 "b33d692198d4715b39008b53dda0584af6cd07dd602034c430852db6c336d2ba"

      define_method(:install) do
        bin.install "toolbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiborhercz/toolbox/releases/download/v0.8.1/toolbox_0.8.1_linux_amd64.tar.gz"
      sha256 "a1f94e562ce58bfe216802f7da915dab967e07c65b1c1a095fdf49d054482a16"
      define_method(:install) do
        bin.install "toolbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiborhercz/toolbox/releases/download/v0.8.1/toolbox_0.8.1_linux_arm64.tar.gz"
      sha256 "2061249f67463eb929da7667080c8076a0fa5c4929c2e0be81cae1ce25edc27d"
      define_method(:install) do
        bin.install "toolbox"
      end
    end
  end

  test do
    system "#{bin}/toolbox -v"
  end
end
