# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolbox < Formula
  desc "A collection of various cli tools"
  homepage "https://github.com/tiborhercz/toolbox"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiborhercz/toolbox/releases/download/v0.8.0/toolbox_0.8.0_darwin_amd64.tar.gz"
      sha256 "ee36f75aa94265dfdba617971afdf3b48493a9eb466195363a5148cf6bde7490"

      define_method(:install) do
        bin.install "toolbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiborhercz/toolbox/releases/download/v0.8.0/toolbox_0.8.0_darwin_arm64.tar.gz"
      sha256 "3a07b1caabd426bea8394fdf31e61e9b26c41925778ef0c3ab0274f1d3dad392"

      define_method(:install) do
        bin.install "toolbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiborhercz/toolbox/releases/download/v0.8.0/toolbox_0.8.0_linux_amd64.tar.gz"
      sha256 "d33869441655344c2f8f3ab56d36d6168e166a9099c8ef24092231ef4c2e36a9"
      define_method(:install) do
        bin.install "toolbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiborhercz/toolbox/releases/download/v0.8.0/toolbox_0.8.0_linux_arm64.tar.gz"
      sha256 "ecf6067aa8df824e0e06ff09ec05fadc756fe38c2d74769d661aa248ecfcf3b5"
      define_method(:install) do
        bin.install "toolbox"
      end
    end
  end

  test do
    system "#{bin}/toolbox -v"
  end
end
